site_name: NFDI Jupyter Services
site_description: A list of jupyter services within the national research data infrastructure of Germany
site_author: WG RSE, NFDI Section Common Infrastructures
site_url: "https://NFDI-Jupyter.github.io/services"

theme:
  name: material
  palette:
    scheme: default
    primary: light blue
    accent: deep purple
  font: false
  logo: assets/nfdi_rgb_Wortmarke_Zusatz_hoch.png
  favicon: assets/nfdi_rgb_Wortmarke.png
  language: en
  features:
    - content.tooltips
  #  - navigation.tabs
  custom_dir: custom/

extra_css:
  - css/neoteroi-cards.css
  - css/extra.css
  - css/hint.min.css

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - js/tablesort.js

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - meta
  - tables
  - def_list
  - neoteroi.cards
  - abbr
  - attr_list
  - pymdownx.snippets

plugins:
  - search
  - tooltips
  - gen-files:
      scripts:
        - docs/gen_detail_pages.py
  - macros:
      include_dir: include
      include_yaml:
        - data/kernels_and_extensions.yml
  - mkdocs-simple-hooks:
      hooks:
        on_pre_build: "data.hooks:generate_cards"
