site_name: ""
site_description: Jupyter4NFDI project overview
site_author: WG RSE, NFDI Section Common Infrastructures, Jupyter4NFDI
site_url: "https://NFDI-Jupyter.github.io/services"
repo_url: https://github.com/NFDI-Jupyter/services
theme:
  name: material 
  features:
    - nagivation.tabs
    - navigation.sections
    - navigation.collapse
    - navigation.footer
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  font:
    text: Fira Sans
    code: Roboto Mono
    icon: 'mdi'
  favicon: images/nfdi_rgb_Wortmarke.png
  logo: ./images/Jupyter4NFDI-top.png
  custom_dir: docs/custom
  #palette:
 #   - scheme: fzj
 #     primary: teal
 #     accent: purple
  palette:
    - scheme: default

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - js/tablesort.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - md_in_html
  - meta
  - tables
  - def_list
  - neoteroi.cards
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - css/style.css
  - css/neoteroi-cards.css
  - css/extra.css

extra:
  logo: "images/logo.png"
  generator: false
  social:
      - icon: fontawesome/brands/github
        link: https://github.com/NFDI-Jupyter/services
  footer:
      logo:
        link: https://www.dfg.de/
        img: images/dfg_logo_schriftzug_weiss_foerderung_en.gif

footer:
  copyright: |
    &copy; 2026 Forschungszentrum JÃ¼lich
  lines: 
    - "Partially funded by DFG as part of NFDI."
    - "Grant Number 521453681"
  links:
    - name: Contact
      link: https://nfdi-jupyter.de/support/
    - name: Legal Notice
      link: https://nfdi-jupyter.de/imprint/
    - name: Privacy Policy
      link: https://hub.nfdi-jupyter.de/hub/privacy

nav:
  - General:
    - Overview: index.md
    - Authentication: authentication_IAM4NFDI.md
    - 2-Factor authentication: 2fa.md
    - Available Resources and Tools: features.md
  - For Users:
    - JupyterLab: users/jupyterlab/default/index.md
    - JupyterLab XL: users/jupyterlab/4.3/index.md
    - Custom Docker Images: users/jupyterlab/customdockerimage/index.md
    - Repo2Docker ( Binder ): users/jupyterlab/repo2docker/index.md
    - Credits: users/credits.md
    - Mount external storage locations: users/storage.md
    - Real-Time-Collaboration (RTC): users/rtc.md
    - Share Links (FAIR): users/share.md
  - For Workshops:
    - Manage Workshops: workshops.md
  - For Resource Providers:
    - Overview: providers/index.md
    - Architecture: providers/architecture.md
    - Installation: providers/installation.md
    - Configuration: providers/configuration.md
  - JupyterHubs within NFDI:
    - Overview: hubs/index.md
    - Statistics about the Jupyter services collected: hubs/stats.md
    - Join the list: hubs/template.md
  - Support: support.md
  - Event: love_data_week_2026.md


plugins:
  - search
  - mkdocs-jupyter
#  - awesome-pages
  - gen-files:
      scripts:
        - docs/hubs/plugins/gen_detail_pages.py
  - macros:
      include_dir: include
  - mkdocs-simple-hooks:
      hooks:
        on_pre_build: "docs.hubs.plugins.hooks:generate_cards"
